language: php

sudo: false

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'

before_script: composer install

script: phpunit --configuration phpunit.xml

notifications:
  slack: bayard-web:VU1TQuHRTQAJj1PSFGx79S4J