language: php

sudo: false

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'

before_script:
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - phpunit --configuration phpunit.xml --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack: bayard-web:VU1TQuHRTQAJj1PSFGx79S4J
